import type { LevelConfig } from './types';

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: '新手启航',
    description: '熟悉滑动操作与射击',
    targetProgress: 30,
    spawnRate: 2.0,
    enemySpeedMultiplier: 1.0,
    maxEnemies: 3,
    enemyTypes: ['drone'],
    bossLevel: false,
    starRequirements: [1, 2, 3],
  },
  {
    id: 2,
    name: '初遇抵抗',
    description: '击杀 40 架敌机',
    targetProgress: 40,
    spawnRate: 1.5,
    enemySpeedMultiplier: 1.1,
    maxEnemies: 4,
    enemyTypes: ['drone'],
    bossLevel: false,
    starRequirements: [1, 2, 3],
  },
  {
    id: 3,
    name: '陨石地带',
    description: '生存并达到进度 100%',
    targetProgress: 50,
    spawnRate: 1.0,
    enemySpeedMultiplier: 1.1,
    maxEnemies: 5,
    enemyTypes: ['drone', 'heavy'],
    bossLevel: false,
    starRequirements: [1, 2, 3],
  },
  {
    id: 4,
    name: '弹幕威胁',
    description: '击杀包含新型敌人的混合编队',
    targetProgress: 60,
    spawnRate: 1.2,
    enemySpeedMultiplier: 1.2,
    maxEnemies: 5,
    enemyTypes: ['drone', 'scout'],
    bossLevel: false,
    starRequirements: [1, 2, 3],
  },
  {
    id: 5,
    name: '精英小队',
    description: '击败指定数量的精英敌人',
    targetProgress: 70,
    spawnRate: 1.5,
    enemySpeedMultiplier: 1.2,
    maxEnemies: 4,
    enemyTypes: ['drone', 'scout', 'heavy'],
    bossLevel: false,
    starRequirements: [1, 2, 3],
  },
  {
    id: 6,
    name: '左右包夹',
    description: '达到进度 100%',
    targetProgress: 80,
    spawnRate: 0.8,
    enemySpeedMultiplier: 1.3,
    maxEnemies: 6,
    enemyTypes: ['drone', 'scout', 'heavy'],
    bossLevel: false,
    starRequirements: [1, 2, 3],
  },
  {
    id: 7,
    name: '机动闪避',
    description: '躲避密集的敌机编队',
    targetProgress: 90,
    spawnRate: 0.6,
    enemySpeedMultiplier: 1.4,
    maxEnemies: 7,
    enemyTypes: ['drone', 'scout', 'heavy'],
    bossLevel: false,
    starRequirements: [1, 2, 3],
  },
  {
    id: 8,
    name: '地毯式轰炸',
    description: '达到进度 100%',
    targetProgress: 100,
    spawnRate: 0.5,
    enemySpeedMultiplier: 1.5,
    maxEnemies: 8,
    enemyTypes: ['drone', 'scout', 'heavy', 'suicide'],
    bossLevel: false,
    starRequirements: [1, 2, 3],
  },
  {
    id: 9,
    name: '母舰阴影',
    description: '击毁小型母舰',
    targetProgress: 100,
    spawnRate: 1.0,
    enemySpeedMultiplier: 1.3,
    maxEnemies: 3,
    enemyTypes: ['drone', 'scout'],
    bossLevel: true,
    starRequirements: [1, 2, 3],
  },
  {
    id: 10,
    name: '雷电风暴',
    description: '终极挑战，混合所有敌人类型',
    targetProgress: 120,
    spawnRate: 0.4,
    enemySpeedMultiplier: 1.8,
    maxEnemies: 10,
    enemyTypes: ['drone', 'scout', 'heavy', 'suicide'],
    bossLevel: true,
    starRequirements: [1, 2, 3],
  },
];

export function getLevelConfig(levelId: number): LevelConfig {
  return LEVELS[levelId - 1] || LEVELS[0];
}
