import http from 'node:http';
import type { Socket } from 'node:net';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { RoomManager } from './roomManager.ts';
import { WebSocketConnection } from './websocket.ts';
import type {
  ClientMessage,
  ErrorEvent,
  ServerMessage,
  StartMatchResponse,
  MatchParticipant,
  UploadDefenseRequest,
} from '../src/game/multiplayer/protocol.ts';
import type { BattleReport, BattleState } from '../src/game/battle/index.ts';
import type { RoomInfo } from '../src/game/multiplayer/protocol.ts';
import { parseImportUrl, normalizeBotPolicy, parseModulesFromUrl } from '../src/game/bots/index.ts';

type MatchServerMessage = ServerMessage<BattleState, BattleReport>;

const PORT = Number(process.env.PORT ?? 3001);
const HOST = process.env.HOST ?? '0.0.0.0';

const roomManager = new RoomManager();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DIST_DIR = path.join(__dirname, '../dist');

function saveAgentGatewayFile(roomCode: string, playerId: string) {
  try {
    const key = `ASTRA-GATEWAY-${roomCode}-${playerId.slice(0, 6).toUpperCase()}`;
    const payload = {
      gatewayKey: key,
      roomCode,
      playerId,
      endpoint: `http://localhost:3001/api/agent/strategy`,
      wsEndpoint: `ws://localhost:3001/ws`,
      updatedAt: new Date().toISOString(),
      instructions: "This file is automatically generated by the Storm Blaster game server. AI coding agents (like Claude code, codex, kimi code, or Antigravity) can read this file to obtain the Gateway Key and automatically connect and push strategies to the game client!"
    };
    const filePath = path.join(__dirname, '../agent-gateway.json');
    const hiddenFilePath = path.join(__dirname, '../.agent-gateway.json');
    fs.writeFileSync(filePath, JSON.stringify(payload, null, 2), 'utf-8');
    fs.writeFileSync(hiddenFilePath, JSON.stringify(payload, null, 2), 'utf-8');
    console.log(`[Agent Gateway] Saved active key and config to ${filePath}`);
  } catch (err) {
    console.error(`[Agent Gateway] Failed to write agent gateway file:`, err);
  }
}

const server = http.createServer((request, response) => {
  // Expose CORS headers for easy Agent API access
  response.setHeader('Access-Control-Allow-Origin', '*');
  response.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  response.setHeader('Access-Control-Allow-Headers', 'Content-Type, X-Agent-Gateway-Key');

  if (request.method === 'OPTIONS') {
    response.writeHead(204);
    response.end();
    return;
  }

  if (request.url === '/healthz') {
    response.writeHead(200, { 'content-type': 'application/json' });
    response.end(JSON.stringify({ ok: true }));
    return;
  }

  // REST API Route to Save Active Gateway Key to local workspace file
  if (request.method === 'POST' && request.url === '/api/agent/save-key') {
    let body = '';
    request.on('data', (chunk) => {
      body += chunk;
    });
    request.on('end', () => {
      try {
        const payload = JSON.parse(body) as { roomCode: string; playerId: string };
        const { roomCode, playerId } = payload;
        
        if (!playerId) {
          response.writeHead(400, { 'content-type': 'application/json' });
          response.end(JSON.stringify({ error: 'Missing playerId' }));
          return;
        }

        saveAgentGatewayFile(roomCode || 'LOBBY', playerId);

        response.writeHead(200, { 'content-type': 'application/json' });
        response.end(JSON.stringify({ ok: true, key: `ASTRA-GATEWAY-${roomCode || 'LOBBY'}-${playerId.slice(0, 6).toUpperCase()}` }));
      } catch (err) {
        response.writeHead(500, { 'content-type': 'application/json' });
        response.end(JSON.stringify({ error: err instanceof Error ? err.message : 'Invalid JSON payload' }));
      }
    });
    return;
  }

  // REST API Route for Autonomous Agent Strategy Push Gateway
  if (request.method === 'POST' && request.url === '/api/agent/strategy') {
    let body = '';
    request.on('data', (chunk) => {
      body += chunk;
    });
    request.on('end', () => {
      try {
        const payload = JSON.parse(body) as { key: string; strategyUrl: string };
        const { key, strategyUrl } = payload;
        
        if (!key || !strategyUrl) {
          response.writeHead(400, { 'content-type': 'application/json' });
          response.end(JSON.stringify({ error: 'Missing key or strategyUrl fields' }));
          return;
        }

        // Key Format: ASTRA-GATEWAY-${roomCode}-${playerId}
        const parts = key.split('-');
        if (parts[0] !== 'ASTRA' || parts[1] !== 'GATEWAY' || parts.length < 4) {
          response.writeHead(400, { 'content-type': 'application/json' });
          response.end(JSON.stringify({ error: 'Malformed gateway key' }));
          return;
        }

        const roomCode = parts[2];
        const playerId = parts.slice(3).join('-');

        const room = roomManager.getRoomByCode(roomCode);
        if (!room) {
          response.writeHead(404, { 'content-type': 'application/json' });
          response.end(JSON.stringify({ error: `Room ${roomCode} not found` }));
          return;
        }

        if (!room.hasPlayer(playerId)) {
          response.writeHead(404, { 'content-type': 'application/json' });
          response.end(JSON.stringify({ error: 'Pilot not found in room' }));
          return;
        }

        // Parse and compile policy
        const policy = normalizeBotPolicy(parseImportUrl(strategyUrl));
        
        // Parse modules from strategyUrl if present, otherwise fallback to existing
        const parsedModules = parseModulesFromUrl(strategyUrl);
        const roomInfo = room.getRoomInfo(playerId);
        const participant = roomInfo.participants.find((entry) => entry.playerId === playerId);
        const finalModules = parsedModules.length > 0 ? parsedModules : (participant?.bot?.modules ?? []);

        // Update server-authoritative bot selection
        roomManager.selectBot(room.roomId, playerId, {
          botId: 'llm-strategy',
          label: 'Agent (Gateway)',
          difficulty: 'normal',
          modules: finalModules,
          policy,
        });

        response.writeHead(200, { 'content-type': 'application/json' });
        response.end(JSON.stringify({ ok: true, message: 'Strategy successfully injected!' }));
      } catch (error) {
        response.writeHead(500, { 'content-type': 'application/json' });
        response.end(JSON.stringify({ error: error instanceof Error ? error.message : 'Invalid JSON payload' }));
      }
    });
    return;
  }

  let filePath = path.join(DIST_DIR, request.url || '/');

  if (!filePath.startsWith(DIST_DIR)) {
    response.writeHead(403);
    response.end('Forbidden');
    return;
  }

  try {
    const stats = fs.statSync(filePath);
    if (stats.isDirectory()) {
      filePath = path.join(filePath, 'index.html');
    }
  } catch {
    filePath = path.join(DIST_DIR, 'index.html');
  }

  const ext = path.extname(filePath).toLowerCase();
  const mimeTypes: Record<string, string> = {
    '.html': 'text/html',
    '.css': 'text/css',
    '.js': 'text/javascript',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.gif': 'image/gif',
    '.svg': 'image/svg+xml',
    '.ico': 'image/x-icon',
    '.json': 'application/json',
  };
  const contentType = mimeTypes[ext] || 'application/octet-stream';

  fs.readFile(filePath, (error, content) => {
    if (error) {
      response.writeHead(404, { 'content-type': 'text/plain' });
      response.end('404 Not Found');
    } else {
      response.writeHead(200, { 'content-type': contentType });
      response.end(content, 'utf-8');
    }
  });
});

import { LeaderboardManager } from './leaderboardManager.ts';

const leaderboardManager = new LeaderboardManager();
const activeConnections = new Set<WebSocketConnection>();

server.on('upgrade', (request, socket, head) => {
  if (request.url !== '/ws') {
    socket.destroy();
    return;
  }

  void head;

  let connection: WebSocketConnection;
  try {
    connection = new WebSocketConnection(socket as Socket, request);
  } catch {
    socket.destroy();
    return;
  }

  activeConnections.add(connection);

  connection.onMessage((rawMessage) => {
    handleMessage(connection, rawMessage);
  });

  connection.on('close', () => {
    activeConnections.delete(connection);
    roomManager.disconnect(connection);
  });
});

server.listen(PORT, HOST, () => {
  console.log(`Battle room server listening on http://${HOST}:${PORT}`);
  console.log(`WebSocket endpoint ready at ws://${HOST}:${PORT}/ws`);
});

function handleMessage(connection: WebSocketConnection, rawMessage: string): void {
  let message: unknown;

  try {
    message = JSON.parse(rawMessage);
  } catch {
    sendError(connection, 'invalid_json', 'Message body must be valid JSON.', false);
    return;
  }

  if (!isClientMessage(message)) {
    sendError(connection, 'invalid_message', 'Message envelope is not valid.', false);
    return;
  }

  try {
    switch (message.type) {
      case 'room.create': {
        const room = roomManager.createRoom(message.payload, connection);
        send(connection, {
          v: 1,
          type: 'room.created',
          payload: {
            room: room.getRoomInfo(message.payload.playerId),
          },
        });
        return;
      }
      case 'room.join': {
        const room = roomManager.joinRoom(message.payload, connection);
        send(connection, {
          v: 1,
          type: 'room.joined',
          payload: {
            room: room.getRoomInfo(message.payload.playerId),
          },
        });
        return;
      }
      case 'match.bot.select': {
        const room = requireRoom(roomManager, message.payload.roomId);
        roomManager.selectBot(message.payload.roomId, message.payload.playerId, message.payload.bot);
        send(connection, {
          v: 1,
          type: 'match.bot.selected',
          payload: {
            room: room.getRoomInfo(message.payload.playerId),
            participant: toMatchParticipant(room, message.payload.playerId),
          },
        });
        return;
      }
      case 'room.ready': {
        const room = requireRoom(roomManager, message.payload.roomId);
        roomManager.setReady(message.payload.roomId, message.payload.playerId, message.payload.ready);
        send(connection, {
          v: 1,
          type: 'room.readied',
          payload: {
            room: room.getRoomInfo(message.payload.playerId),
            participant: toRoomParticipant(room, message.payload.playerId),
          },
        });
        return;
      }
      case 'match.start': {
        const snapshot = roomManager.startMatch(message.payload.roomId, message.payload.playerId);
        send(connection, {
          v: 1,
          type: 'match.started',
          payload: {
            matchId: snapshot.matchId,
            phase: 'running',
          } satisfies StartMatchResponse,
        });
        return;
      }
      case 'agent.connect': {
        const { key } = message.payload as { key: string };
        if (!key) {
          sendError(connection, 'invalid_payload', 'Missing key in payload.', false);
          return;
        }

        const parts = key.split('-');
        if (parts[0] !== 'ASTRA' || parts[1] !== 'GATEWAY' || parts.length < 4) {
          sendError(connection, 'invalid_key', 'Malformed gateway key.', false);
          return;
        }

        const roomCode = parts[2];
        const playerId = parts.slice(3).join('-');

        const room = roomManager.getRoomByCode(roomCode);
        if (!room) {
          sendError(connection, 'room_not_found', `Room ${roomCode} not found.`, false);
          return;
        }

        if (!room.hasPlayer(playerId)) {
          sendError(connection, 'player_not_found', 'Player not found in room.', false);
          return;
        }

        // Attach Agent WebSocket connection
        room.attachAgentConnection(playerId, connection);
        
        // Confirm connection back to the Agent
        send(connection, {
          v: 1,
          type: 'room.updated',
          payload: {
            room: room.getRoomInfo(playerId),
          },
        });
        return;
      }
      case 'agent.strategy': {
        const { key, strategyUrl } = message.payload as { key: string; strategyUrl: string };
        if (!key || !strategyUrl) {
          sendError(connection, 'invalid_payload', 'Missing key or strategyUrl in payload.', false);
          return;
        }

        const parts = key.split('-');
        if (parts[0] !== 'ASTRA' || parts[1] !== 'GATEWAY' || parts.length < 4) {
          sendError(connection, 'invalid_key', 'Malformed gateway key.', false);
          return;
        }

        const roomCode = parts[2];
        const playerId = parts.slice(3).join('-');

        const room = roomManager.getRoomByCode(roomCode);
        if (!room) {
          sendError(connection, 'room_not_found', `Room ${roomCode} not found.`, false);
          return;
        }

        if (!room.hasPlayer(playerId)) {
          sendError(connection, 'player_not_found', 'Player not found in room.', false);
          return;
        }

        // Parse strategy URL and update bot policy
        const policy = normalizeBotPolicy(parseImportUrl(strategyUrl));
        const roomInfo = room.getRoomInfo(playerId);
        const participant = roomInfo.participants.find((p) => p.playerId === playerId);
        const existingModules = participant?.bot?.modules ?? [];

        roomManager.selectBot(room.roomId, playerId, {
          botId: 'llm-strategy',
          label: 'Agent (Gateway)',
          difficulty: 'normal',
          modules: existingModules,
          policy,
        });
        return;
      }
      case 'ladder.get': {
        const { playerId } = message.payload as { playerId: string };
        if (playerId) {
          connection.playerId = playerId;
        }
        const list = leaderboardManager.getEntries();
        const personal = leaderboardManager.getEntry(playerId);
        const rank = list.findIndex((e) => e.playerId === playerId) + 1;

        send(connection, {
          v: 1,
          type: 'ladder.sync',
          payload: {
            leaderboard: list,
            personalRank: rank > 0 ? rank : list.length + 1,
            personalScore: personal ? personal.score : 1000,
            personalCombatPower: personal ? personal.combatPower : 2000,
          },
        });
        return;
      }
      case 'ladder.upload_defense': {
        const payload = message.payload as UploadDefenseRequest;

        leaderboardManager.updatePlayerDefense(
          payload.playerId,
          payload.displayName,
          payload.modules,
          payload.botKind,
          payload.policy
        );

        broadcastLadderUpdate();
        return;
      }
      case 'ladder.battle_result': {
        const { challengerId, opponentId, outcome } = message.payload as {
          challengerId: string;
          opponentId: string;
          outcome: 'win' | 'lose';
        };

        const result = leaderboardManager.processBattleResult(challengerId, opponentId, outcome);

        broadcastLadderUpdate(result.challengerChange, result.opponentChange);
        return;
      }
    }
  } catch (error) {
    sendError(connection, 'room_error', error instanceof Error ? error.message : 'Room operation failed.', true);
  }
}

function broadcastLadderUpdate(challengerChange?: number, opponentChange?: number): void {
  const list = leaderboardManager.getEntries();
  for (const conn of activeConnections) {
    if (!conn.isOpen()) continue;

    const playerId = conn.playerId || '';
    const personal = leaderboardManager.getEntry(playerId);
    const rank = list.findIndex((e) => e.playerId === playerId) + 1;

    conn.sendJson({
      v: 1,
      type: 'ladder.sync',
      payload: {
        leaderboard: list,
        personalRank: rank > 0 ? rank : list.length + 1,
        personalScore: personal ? personal.score : 1000,
        personalCombatPower: personal ? personal.combatPower : 2000,
        challengerChange,
        opponentChange,
      },
    });
  }
}

function send(connection: WebSocketConnection, message: MatchServerMessage): void {
  connection.sendJson(message);
}

function sendError(connection: WebSocketConnection, code: string, message: string, recoverable: boolean): void {
  const payload: ErrorEvent = {
    error: {
      code,
      message,
      recoverable,
    },
  };

  send(connection, {
    v: 1,
    type: 'error',
    payload,
  });
}

function isClientMessage(value: unknown): value is ClientMessage {
  if (typeof value !== 'object' || value === null) return false;
  const record = value as Record<string, unknown>;
  return record.v === 1 && typeof record.type === 'string' && typeof record.payload === 'object' && record.payload !== null;
}

function toMatchParticipant(room: { getRoomInfo: (playerId: string) => RoomInfo }, playerId: string): MatchParticipant {
  const info = room.getRoomInfo(playerId);
  const participant = info.participants.find((entry) => entry.playerId === playerId);
  if (!participant) {
    throw new Error('Participant was not found in room state.');
  }

  return {
    playerId: participant.playerId,
    displayName: participant.displayName,
    bot: participant.bot ?? undefined,
    connected: participant.connected,
  };
}

function toRoomParticipant(room: { getRoomInfo: (playerId: string) => RoomInfo }, playerId: string) {
  const info = room.getRoomInfo(playerId);
  const participant = info.participants.find((entry) => entry.playerId === playerId);
  if (!participant) {
    throw new Error('Participant was not found in room state.');
  }

  return participant;
}

function requireRoom(roomManagerInstance: RoomManager, roomId: string) {
  const room = roomManagerInstance.getRoom(roomId);
  if (!room) {
    throw new Error(`Room ${roomId} was not found.`);
  }

  return room;
}
